"""Add Applicant and TechSkills table.

Revision ID: 15a32679fcea
Revises: 
Create Date: 2020-02-15 13:02:28.280680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a32679fcea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('country_of_residence', sa.String(), nullable=True),
    sa.Column('nacionality', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('techskills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicants_tech_skills',
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('techskill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['techskill_id'], ['techskills.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicants_tech_skills')
    op.drop_table('techskills')
    op.drop_table('applicants')
    # ### end Alembic commands ###
