"""Change applicant model age to birthdays and make location fields nullables.

Revision ID: 6a67d4cb8923
Revises: b48c80ebebc6
Create Date: 2020-03-11 11:41:43.016484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a67d4cb8923'
down_revision = 'b48c80ebebc6'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('birthday', sa.Date(), nullable=False))
    op.add_column('applicants', sa.Column('photo', sa.String(), nullable=False))
    op.alter_column('applicants', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applicants', 'nacionality',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('applicants', 'salary_expectancy',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('applicants', 'age')
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('applicants', 'salary_expectancy',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('applicants', 'nacionality',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('applicants', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('applicants', 'photo')
    op.drop_column('applicants', 'birthday')
    # ### end Alembic commands ###
