"""Added general knowledge

Revision ID: 846bf0b3e931
Revises: c988854adf66
Create Date: 2020-02-20 00:08:27.024274

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '846bf0b3e931'
down_revision = 'c988854adf66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('general_knowledge',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('description', sa.String(length=255), nullable=False),
                    sa.Column('applicant_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('general_knowledge')
    # ### end Alembic commands ###
