"""Applicant tech skills

Revision ID: b48c80ebebc6
Revises: 57c4b90a3a27
Create Date: 2020-02-21 00:32:09.813161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48c80ebebc6'
down_revision = '57c4b90a3a27'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants_tech_skills', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('applicants_tech_skills', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicants_tech_skills', 'updated_at')
    op.drop_column('applicants_tech_skills', 'created_at')
    # ### end Alembic commands ###
