"""Added missing field to applicant

Revision ID: c988854adf66
Revises: 7aa90d25d245
Create Date: 2020-02-19 23:37:12.227415

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c988854adf66'
down_revision = '7aa90d25d245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('email', sa.String(), nullable=False))
    op.add_column('applicants', sa.Column('salary_expectancy', sa.Float(), nullable=False))
    op.alter_column('applicants', 'address',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('applicants', 'age',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('applicants', 'fullname',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('applicants', 'nacionality',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.create_unique_constraint(None, 'applicants', ['email'])
    op.drop_constraint('techskills_name_key', 'techskills', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('techskills_name_key', 'techskills', ['name'])
    op.alter_column('applicants', 'nacionality',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('applicants', 'fullname',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('applicants', 'age',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('applicants', 'address',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('applicants', 'salary_expectancy')
    op.drop_column('applicants', 'email')
    # ### end Alembic commands ###
